name: "CI"

permissions: "read-all"

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: "bash"

env:
  FORCE_COLOR: "1"
    
jobs:
  ruff:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "astral-sh/ruff-action@v3"
        with:
          src: "./src"

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    name: "Test (${{ matrix.python-version }})"
    runs-on: "ubuntu-latest"
    continue-on-error: false

    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v4"

    - name: "Setup Python"
      uses: "actions/setup-python@v4"
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: "Run tests"
      run: |
        uv sync --extra test --python="${{ matrix.python-version }}"
        uv run pytest
