name: "Codecov"

on:
  push:
    branches:
      - "main"

jobs:
  coverage:
    runs-on: "ubuntu-latest"
    env:
      OS: "ubuntu-latest"
      PYTHON: "3.9"
    environment:
      name: "codecov"
    steps:
    - uses: "actions/checkout@master"

    - name: "Setup Python"
      uses: "actions/setup-python@master"
      with:
        python-version: "3.9"

    - name: "Generate coverage report"
      run: |
        python -m pip install poetry
        poetry install --with test
        poetry run pytest --cov=src/powerline_k8s --cov-report=xml

    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v4"
      with:
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}