name: "Codecov"

on: [push]

jobs:
  coverage:
    runs-on: "ubuntu-latest"
    env:
      OS: "ubuntu-latest"
      PYTHON: '3.10'
    environment:
      name: "codecov"
    steps:
    - uses: "actions/checkout@master"

    - name: "Setup Python"
      uses: "actions/setup-python@master"
      with:
        python-version: "3.10"

    - name: "Generate coverage report"
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v4"
      with:
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}