name: Publish docs to GitHub Pages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup uv"
        uses: "astral-sh/setup-uv@v6"
        with:
          python-version: "3.10"

      - name: "Generate docs"
        run: |
          uv sync --extra docs --python
          uv run pdoc -o docs src/powerline_k8s

      - name: "Publish docs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
